name: Main workflow

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.x"
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal --filter "Category!=LongRunning"
      - name: Publish
        run: dotnet publish -c Release -o artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: ./artifact/
